services:
    awaresoft.menu.admin.menu:
        class: Awaresoft\MenuBundle\Admin\MenuAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin.admin.menu_group_site_builder, label: menu.admin.menu.menu }
        arguments:
            - null
            - Awaresoft\MenuBundle\Entity\Menu
            - AwaresoftMenuBundle:MenuCRUD
            - '@service_container'
            - '@awaresoft.setting'
        calls:
            - [setSiteManager, ["@sonata.page.manager.site"]]
            - [setTemplate, [tree, 'AwaresoftMenuBundle:CRUD:tree.html.twig']]